name: CI/CD Pipeline

on:
  push:
    branches: ["main"]   # or master
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build API image
      - name: Build API Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/voice-assistant-api:latest ./api

      # Push API image
      - name: Push API image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/voice-assistant-api:latest
